#!/bin/python3
import requests as rq
import urllib.request as ur
import sys
import yaml
import os
from src.colors import *

PATH = "/tnam"

_help = \
"""
Syntax: tnam [command] [package] [*args]

Commands:
install - install a package
remove - remove a package
help - this text

Arguments:
-d | --dev - gets access to developer functions
"""


def err(*text):
    print(Text.RED + Styles.BOLD + 'Error: ', Styles.RESET, *text, sep='')


def mark(*text):
    print(Text.YELLOW + Styles.BOLD + 'Mark: ', Styles.RESET, *text, sep='')


def init():
    mark('Function in development.')
    os.system(f'mkdir {PATH}/temp')
    os.system(f'mkdir {PATH}/usr')
    os.system(f'touch {PATH}/usr/installed.yaml')


def update(dev=False):
    if not dev:
        mark('Function in development.')


def readYaml(path) -> dict:

    with open(f'{path}', 'r') as f:
        data = yaml.safe_load(f)
        f.close()

    return data


def unzip(file, path):
    os.system(f'unzip -q -f -d {path} {file}')
    print(f'Unpacking …{file}')


def clearTemp():
    os.system(f'rm -rf {PATH}/temp/*')


def remove(package):
    os.system(f'dpkg -r {package}')


def resourcesList() -> list:

    deb_sources = readYaml(f'{PATH}/src/sources.yaml')

    return deb_sources['deb']


def filesList(package, resource) -> list:
    
    with open(f'{PATH}/temp/files.yaml', 'wb') as bin:

        bin.write(x := rq.get(f'https://raw.githubusercontent.com/{resource}/files.yaml').content)
        bin.close()
    
    files = readYaml(f'{PATH}/temp/files.yaml')
    
    clearTemp()

    return files[package]['files']


def install(package):

    resource = resourcesList()[0]

    try:
        fileList = filesList(package, resource)
    except KeyError:
        err("This package doesn't exist.")
        return

    ur.urlretrieve(f'https://raw.githubusercontent.com/{resource}/{fileList[0]}', f'{PATH}/temp/{fileList[0]}')
    unzip(f'{PATH}/temp/{fileList[0]}', f'{PATH}/temp/')
    
    for f in os.listdir(f'{PATH}/temp'):
        if f.endswith('.deb'): os.system(f'dpkg -i {PATH}/temp/{f}')

    clearTemp()
    print(f'{package} successfully installed.')

def isSudo():
    if os.geteuid() != 0:
        err('Not a sudo user.')
        return False
    return True

def main():
    argv = sys.argv[1:]

    if not argv: 
        print('The needed app manager.')
        mark('Type "tham help" for help.')
        return
    
    match argv[0]:
        case 'init':
            init()
        case 'install':
            if isSudo():
                install(argv[1])
        case 'help':
            print(_help)
        case 'remove':
            if isSudo():
                remove(argv[1])
        case 'update':
            if isSudo():
                update()
        case _:
            print("Wrong command. Type 'tnam help' for help")


if __name__ == '__main__':
    main()
